apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-ing  
spec:
  rules:
    - host: test-ing.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: caddy-svc
                port:
                  number: 80
