apiVersion: v1
kind: Pod
metadata:
  name: node-affinity-demo
  labels:
    env: staging
spec:
  containers:
  - name: node-affinity-demo
    image: nginx
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: size
            operator: In
            values:
            - large
            - small
